export const projects = [
  {
    id: 1,
    title: 'Excel & Azure Integration',
    description: 'Utilized advanced Excel features (Macros, Solver, Goal Seek) and Azure decision trees to analyze company data and generate actionable insights.',
    type: 'Data Analysis',
    icon: '📊',
    tech: ['Excel', 'VBA', 'Macros', 'Azure', 'Solver'],
    liveUrl: '#',
    githubUrl: '#',
  },
  {
    id: 2,
    title: 'SQL Database Modeling & Business Queries',
    description: 'Designed an ERD model, built relational tables in Microsoft Access, and developed complex SQL queries and subqueries to analyze company data.',
    type: 'Database Design',
    icon: '🗄️',
    tech: ['SQL', 'ERD', 'Microsoft Access', 'Database Design'],
    liveUrl: '#',
    githubUrl: '#',
  },
  {
    id: 3,
    title: 'End-to-End Data Analysis (Kaggle Project)',
    description: 'Performed comprehensive analysis of a Kaggle dataset. Processed and cleaned data using Python (Pandas), built an interactive Power BI dashboard, and validated with Excel.',
    type: 'Business Intelligence',
    icon: '📈',
    tech: ['Python', 'Pandas', 'Power BI', 'Excel', 'Kaggle'],
    liveUrl: '#',
    githubUrl: '#',
  },
  {
    id: 4,
    title: 'Sales Performance Dashboard',
    description: 'Created an interactive Power BI dashboard analyzing sales trends, customer segmentation, and revenue forecasting using real-time data integration.',
    type: 'Business Intelligence',
    icon: '💼',
    tech: ['Power BI', 'DAX', 'SQL', 'Excel'],
    liveUrl: '#',
    githubUrl: '#',
  },
  {
    id: 5,
    title: 'Financial Data Analysis with Python',
    description: 'Developed Python scripts to automate financial reporting, perform statistical analysis, and visualize key performance indicators for business stakeholders.',
    type: 'Data Analysis',
    icon: '💰',
    tech: ['Python', 'NumPy', 'Matplotlib', 'Jupyter'],
    liveUrl: '#',
    githubUrl: '#',
  },
  {
    id: 6,
    title: 'Web Scraping & Data Pipeline',
    description: 'Built an automated data pipeline to scrape, clean, and store market data from multiple sources. Implemented scheduling and error handling for reliability.',
    type: 'Data Engineering',
    icon: '🌐',
    tech: ['Python', 'BeautifulSoup', 'Selenium', 'SQL'],
    liveUrl: '#',
    githubUrl: '#',
  },
];